version: '3.7'
services:
  git-wiki-github:
    container_name: git-wiki-github
    build: .
    ports:
     - 4000:4000
     - 35729:35729
    volumes:
     - .:/srv/jekyll
    command: bundle exec jekyll serve --host 0.0.0.0 --force_polling --livereload